"""Admin toggle

Revision ID: 17756ba7350b
Revises: b595c090b9bc
Create Date: 2024-11-14 20:00:15.071177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17756ba7350b'
down_revision = 'b595c090b9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
