"""Initial migration

Revision ID: 21abd75fe10b
Revises: 
Create Date: 2024-11-12 17:27:57.249313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21abd75fe10b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=50), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('stripe_price_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('profile_picture', sa.String(length=150), nullable=True),
    sa.Column('last_signal_reset', sa.DateTime(), nullable=True),
    sa.Column('signals_used', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('allow_marketing_emails', sa.Boolean(), nullable=True),
    sa.Column('share_data_with_partners', sa.Boolean(), nullable=True),
    sa.Column('allow_profile_visibility', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('subscription')
    # ### end Alembic commands ###
