"""Add Notification model

Revision ID: 6c8dd79e00eb
Revises: abcdef123456
Create Date: 2024-11-14 01:10:42.048124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8dd79e00eb'
down_revision = 'abcdef123456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('fk_notification_sender_id', type_='foreignkey')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_notification_sender_id', 'user', ['sender_id'], ['id'])
        batch_op.alter_column('message',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
