"""Add signals_per_day to Subscription model

Revision ID: 6d73958d60e6
Revises: 86f277f1be5f
Create Date: 2024-11-14 23:34:25.340611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d73958d60e6'
down_revision = '86f277f1be5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        # Add the 'signals_per_day' column with a temporary default value (e.g., 5)
        batch_op.add_column(sa.Column('signals_per_day', sa.Integer(), nullable=False, server_default='5'))
    # ### end Alembic commands ###

    # Remove the server_default after ensuring all rows have valid data
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('signals_per_day', server_default=None)


def downgrade():
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('signals_per_day')
