"""Add Setting model

Revision ID: 814d201f6e2c
Revises: c3445fe8b596
Create Date: 2024-11-14 22:02:21.294123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814d201f6e2c'
down_revision = 'c3445fe8b596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
