"""Add sender_id to Notification model

Revision ID: bd27c124a61d
Revises: 6c8dd79e00eb
Create Date: 2024-11-14 16:39:06.730370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd27c124a61d'
down_revision = '6c8dd79e00eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_foreign_key(
            'fk_notification_sender',  # Constraint name
            'user',                    # Referent table
            ['sender_id'],            # Local columns
            ['id']                     # Remote columns
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_sender', type_='foreignkey')
        batch_op.alter_column('message',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
